Include configuration for Country Code header
easybroker/easybroker_gem pull request #5
Opened 2022-08-05 01:43 UTC by okcomputer93

This change includes an option to configure the country
code header so the gem can work with the new integration 
partner endpoints changes.

2022-08-10 18:00 UTC, okcomputer93 commented on lib/easy_broker/api_client.rb
> +      EasyBroker::AUTHORIZATION_HEADER => EasyBroker.configuration.api_key,
Hago merge del country code header de acuerdo al que se configuró, incluí `compact` porque para otros endpoints no es necesario y puede tener el valor por default de `nil`.

2022-08-10 18:00 UTC, okcomputer93 commented on lib/easy_broker/errors.rb
> +      super(response["error"], response)
Apliqué este cambio para usar el mensaje de la respuesta, creo que el grupo de endpoints para integration partners son los únicos en los que retornamos un status `:unauthorized` o 401

2022-08-10 18:00 UTC, okcomputer93 commented on test/test_helper.rb
> +  config.country_code = 'MX'
Configuro `country_code` con `MX` solo para propósitos de testing.

2022-08-10 21:59 UTC, hugobelman requested changes

2022-08-10 21:59 UTC, hugobelman commented on lib/easy_broker/constants.rb
> +  COUNTRY_CODE_HEADER = 'Country-Code'
```suggestion
  COUNTRY_CODE_HEADER  = 'Country-Code'
```

2022-08-10 21:59 UTC, hugobelman commented on lib/easy_broker/errors.rb
> +      super(response["error"], response)
Qué te parece si lo dejamos como antes para evitar problemas de compatibilidad en caso de cambiar los mensajes de error?

2022-08-11 15:15 UTC, hugobelman approved these changes
Luce bien!

2022-08-12 19:34 UTC, merged